/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cmd.h"

bool_t xdr_command (XDR *xdrs, command *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cmd, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
